### PR TITLE
Explicit Application Uploads

### PR DESCRIPTION
**Pull request by kennethreitz**
This adds a basic `mediasync.utils` module available, which contains one function:

**upload**: Uploads a file-like object to the configured backend client.

Ideally, the `syncmedia` management command would utilize this too, in place of the now duplicated code. 
But, this suits my needs for now.

Also, a few other cleanups were added, like moving module logic out of `__init__.py`, and into `core.py`.

---

**Use case:**

I'm uploading non-local media (user avatars) from my application to the configured backend (s3). Multiple frontends.

### CODE REVIEW

**Comment by jcarbaugh** [comment]
Wow. Just noticed this pull request and it looks great! This would go along quite well with some changes that I'd like in a 3.0 release, so I'm going to put out a 2.2.0 now and then merge this in a few days.

Thanks!

**Comment by jcarbaugh** [comment]
I'm not too familiar with the pull requests feature on here. Can you update it to request a pull on 3.0dev branch?

**Comment by kennethreitz** [comment]
No, but you can just merge it in manually:

```
$ git checkout 3.0dev
$ git pull git@github.com:kennethreitz/django-mediasync.git feature/upload
```

Or, I can open a new request. Let me know.

**Comment by jcarbaugh** [comment]
Got this merged into the 3.0dev branch. Thanks!

**Comment by kennethreitz** [comment]
Awesome, thanks! Just realized that I forgot to add myself to AUTHORS, btw.

**Comment by jcarbaugh** [comment]
I'll add you now.

**Pull request closed without merging**
