### PR TITLE
Removing remote serving 'magic'

### PR DESCRIPTION
**Pull request by gtaylor**
First, a little background. I've got a large deployment that we're working on transitioning from serving media in-house, to S3 with django-mediasync. We successfully made the switch, and for a while, everything was great. Until the IE7 users started calling support, saying they were seeing JS errors all over the place. This was due to the way the JS files were being combined, that's another issue we'll have to check for our JS.

To quickly get a fix in, we set MEDIASYNC['SERVE_REMOTE'] = False and reloaded the site. All of the images were correctly loaded from their old URLs, but all of the combo JS/CSS were now trying to load from MEDIA_URL, instead of being split into the files that comprise the combo file. To get the behavior that I wanted (breaking apart all of the combo files back into their multiple files when serving media locally), I would have had to set DEBUG = True. Given that this is a production environment, that is obviously bad.

The solution was to remove the DEBUG checking in mediasync and just using SERVE_REMOTE as the sole means of toggling this. If you think about it, this makes more sense anyway, as the user can still do:

```
MEDIASYNC['SERVE_REMOTE'] = DEBUG
```

The last few commits remove all usage of the DEBUG flag for this purpose. Docs and unit tests have been updated, too. I know this is somewhat of a break in expected behavior, but it really has to be this way for my larger deployment in case we need to switch back after our next attempt.

### CODE REVIEW

**Comment by gtaylor** [comment]
Not sure why a bunch of other commits were in this request. Mostly interested in the stuff starting at commit hash d805b17.

**Comment by gtaylor** [comment]
These additional commits are a re-factor of how settings work. We now have an msettings module, which grabs all of the settings from settings.MEDIASYNC, and puts the values in msettings. If some values are missing from settings.MEDIASYNC, the benefit is that the defaults are decided in one point now, instead of having a bunch of get(settings, 'SERVE_REMOTE', False) scattered around. We avoid troubles if we ever need to change defaults, and avoid errors due to two different defaults for the same existing in different parts of the codebase.

**Comment by gtaylor** [comment]
Also, EMULATE_COMBO = True and SERVE_REMOTE = False now serves the combined files instead of splitting combo files up and serving them separately. This is useful for testing your combo'd/minified files before rolling them out to production blindly.

**Comment by jcarbaugh** [comment]
Finally committed changes for having SERVE_REMOTE be the only thing that determines the location from which media is served. A few other people have told me they are big fans of this change. I tried, but I couldn't bring myself to have it default to False. It defaults to not DEBUG.

I also adopted your msettings idea. The actual implementation caused a bunch of tests to fail because settings weren't persisting between method calls, so I had to do a bit of a rewrite. It's the same basic premise and I really like it!

Thanks for contributing!

**Pull request closed without merging**
